repos:
  - repo: local
    hooks:
      - id: relint
        name: reLint
        description: 'Write your own linting rules using regular expressions.'
        entry: relint
        args: ["--fail-warnings", "--git-diff"]
        language: python
        types: [file]

      - id: bandit
        name: bandit
        description: 'Security linter for Python code.'
        entry: bandit
        args: ["--configfile", "pyproject.toml"]
        language: python

      - id: black
        name: black
        entry: black
        description: 'The uncompromising Python code formatter.'
        args: ["--check", ".", "--diff"]
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort
        args: ["--check-only", "--diff"]
        language: python
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        types: [python]
