name: PyPi Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel twine
    - name: Build dist packages
      run: python setup.py sdist bdist_wheel
    - name: Upload packages
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
